CREATE TABLE IF NOT EXISTS petty_cash_records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL,
  item TEXT NOT NULL,
  type TEXT,
  income REAL,
  expense REAL,
  handler TEXT,
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS petty_cash_counts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL UNIQUE,
  n1000 INTEGER NOT NULL DEFAULT 0,
  n500  INTEGER NOT NULL DEFAULT 0,
  n100  INTEGER NOT NULL DEFAULT 0,
  n50   INTEGER NOT NULL DEFAULT 0,
  n10   INTEGER NOT NULL DEFAULT 0,
  n5    INTEGER NOT NULL DEFAULT 0,
  n1    INTEGER NOT NULL DEFAULT 0,
  counted REAL NOT NULL DEFAULT 0,
  book    REAL NOT NULL DEFAULT 0,
  diff    REAL NOT NULL DEFAULT 0,
  handler TEXT,
  note TEXT,
  created_at TEXT,
  updated_at TEXT
);
